version: "3"
services:
  h2e_ui:
    build:
      context: ./ui/app
    ports:
      - "3000:3000"
    container_name: h2e_ui
    stdin_open: true
    volumes:
      - ./ui/app:/usr/src/app/ui
      - /usr/src/app/ui/node_modules
    environment:
      - CI = true

  h2e_api:
    command: ["sh", "run.sh"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=Testing
      - ENDPOINT=h2e_db:5432
      - USERNAME
      - DB_PWD
      - DB_NAME

  h2e_db:
    ports:
      - "5432:5432"
