version: '3'

services:
  h2e_ui:
    build:
      context: ./ui/app
    ports:
      - "3000:3000"
    container_name: h2e_ui
    stdin_open: true
    volumes:
      - ./ui/app:/usr/src/app/ui
      - /usr/src/app/ui/node_modules

  h2e_api:
    image: "h2e_api:${TAG}"
    container_name: h2e_api
    build: ./backend
    depends_on:
      - h2e_db

  h2e_db:
    image: postgres:latest
    container_name: h2e_db
    environment:
      - POSTGRES_USER=${USERNAME}  
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
