version: "3"
services:
  h2e_ui:
      build:
        context: ./ui/app
      ports:
        - "3000:3000"
      container_name: h2e_ui
      stdin_open: true
      volumes:
         - ./ui/app:/usr/src/app/ui
         - /usr/src/app/ui/node_modules

  h2e_api:
    command: ["sh", "run.sh"]
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./config/env/.env.development.local
    networks:
      - h2e

  h2e_db:
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - h2e

volumes:
  db-data:
    driver: local

networks:
  h2e:
    driver: bridge
