version: "3"
services:
#   h2e_ui:
#     command: ["sh", "run.sh"]
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./ui:/app
#     networks:
#       - h2e

  h2e_api:
    command: ["sh", "run.sh"]
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./config/env/.env.development.local
    networks:
      - h2e

  h2e_db:
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - h2e

volumes:
  db-data:
    driver: local

networks:
  h2e:
    driver: bridge
