"""empty message

Revision ID: e6b2af88ac61
Revises: 370f4a27277b
Create Date: 2020-08-06 17:13:49.449041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6b2af88ac61'
down_revision = '370f4a27277b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_application',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_application_email'), 'tutor_application', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_application_email'), table_name='tutor_application')
    op.drop_table('tutor_application')
    # ### end Alembic commands ###
