"""empty message

Revision ID: f505d0bd023e
Revises: 0278c9a2581a
Create Date: 2020-08-20 21:59:43.969006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f505d0bd023e'
down_revision = '0278c9a2581a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    repeat_type_enum = postgresql.ENUM('DAILY', 'WEEKLY', 'BI_WEEKLY', 'MONTHLY', name='repeat_type', create_type=True,
                                     nullable=False)
    repeat_type_enum.create(op.get_bind())
    op.add_column('schedule_item', sa.Column('repeat_type', sa.Enum('DAILY', 'WEEKLY', 'BI_WEEKLY', 'MONTHLY', name='repeat_type'), nullable=True))
    op.drop_column('schedule_item', 'repeat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_item', sa.Column('repeat', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_column('schedule_item', 'repeat_type')
    # ### end Alembic commands ###
