version: 2.1

orbs:
  python: circleci/python@0.2.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@4.1.0

############
# Workflows
############
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_ui
      - build

##################
# Job Definitions
##################
jobs:
  build_ui:
    working_directory: ~/ui/app
    docker:
        - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ checksum "backend/requirements.txt" }}
      - run:
          working_directory: ./backend
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ checksum "backend/requirements.txt" }}
          paths:
            - 'venv'
      - run:
          working_directory: ./backend
          command: |
            . venv/bin/activate
            pytest
