"""empty message

Revision ID: 0278c9a2581a
Revises: 8e3ade06c992
Create Date: 2020-08-20 15:49:10.706248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0278c9a2581a'
down_revision = '8e3ade06c992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_item',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('repeat', sa.Interval(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('schedule_item__start_time__idx', 'schedule_item', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('schedule_item__start_time__idx', table_name='schedule_item')
    op.drop_table('schedule_item')
    # ### end Alembic commands ###
