"""mailing list

Revision ID: 5d0fee6eff94
Revises: d7d37230a902
Create Date: 2020-08-09 16:34:38.750150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d0fee6eff94'
down_revision = 'd7d37230a902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_list_member',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='mailing_status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailing_list_member_email'), 'mailing_list_member', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailing_list_member_email'), table_name='mailing_list_member')
    op.drop_table('mailing_list_member')
    # ### end Alembic commands ###
