"""empty message

Revision ID: 0ee9bd45612f
Revises: ff1979ba073f
Create Date: 2020-10-13 21:08:08.586741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee9bd45612f'
down_revision = 'ff1979ba073f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('admin_id', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('teams_user_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'teams_user_id')
    op.drop_column('school', 'admin_id')
    # ### end Alembic commands ###
