"""created_at fields for user, application, mailing list

Revision ID: 20492670e416
Revises: 5d0fee6eff94
Create Date: 2020-08-09 16:48:46.797857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20492670e416'
down_revision = '5d0fee6eff94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_list_member', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tutor_application', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('tutor_application', 'created_at')
    op.drop_column('mailing_list_member', 'created_at')
    # ### end Alembic commands ###
