"""empty message

Revision ID: 323e179d63b3
Revises: a0153677218f
Create Date: 2020-10-02 08:37:49.711929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '323e179d63b3'
down_revision = 'a0153677218f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session_status_enum = postgresql.ENUM('PENDING', 'ACCEPTED', name='session_status', create_type=True, nullable=True)
    session_status_enum.create(op.get_bind())
    op.add_column('session', sa.Column('session_status', sa.Enum('PENDING', 'ACCEPTED', name='session_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'status')
    # ### end Alembic commands ###
