"""user timezone

Revision ID: 876343168a3a
Revises: 21bcc774faaf
Create Date: 2020-08-10 20:21:52.369761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876343168a3a'
down_revision = '21bcc774faaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
