"""empty message

Revision ID: 87e71d38bd47
Revises: e7e328c0c62e
Create Date: 2020-08-06 17:32:36.409787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87e71d38bd47'
down_revision = 'e7e328c0c62e'
branch_labels = None
depends_on = None


def upgrade():
    user_type_enum = postgresql.ENUM('STUDENT', 'TUTOR', 'TEACHER', 'ADMIN', name='user_type', create_type=True, nullable=False)
    user_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_application', sa.Column('user', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_tutor_application_user'), 'tutor_application', ['user'], unique=False)
    op.create_foreign_key(None, 'tutor_application', 'user', ['user'], ['id'])
    op.add_column('user', sa.Column('user_type', sa.Enum('STUDENT', 'TUTOR', 'TEACHER', 'ADMIN', name='user_type'), nullable=True))
    op.drop_constraint('user_application_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'application')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('application', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_application_fkey', 'user', 'tutor_application', ['application'], ['id'])
    op.drop_column('user', 'user_type')
    op.drop_constraint(None, 'tutor_application', type_='foreignkey')
    op.drop_index(op.f('ix_tutor_application_user'), table_name='tutor_application')
    op.drop_column('tutor_application', 'user')
    # ### end Alembic commands ###
