"""empty message

Revision ID: ebd28d613499
Revises: 0ee9bd45612f
Create Date: 2020-10-14 10:52:33.501645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebd28d613499'
down_revision = '0ee9bd45612f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', name='session_status'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'COMPLETED', name='session_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'COMPLETED', name='session_status'),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', name='session_status'),
               existing_nullable=True)
    # ### end Alembic commands ###
