"""school signup

Revision ID: ed10d3cbd594
Revises: 876343168a3a
Create Date: 2020-08-11 17:18:43.219975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed10d3cbd594'
down_revision = '876343168a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_application',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_name', sa.String(length=120), nullable=True),
    sa.Column('school_city', sa.String(length=64), nullable=True),
    sa.Column('school_state', sa.String(length=16), nullable=True),
    sa.Column('contact_phone', sa.String(length=14), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_application')
    # ### end Alembic commands ###
