"""empty message

Revision ID: cb7ca032ef2f
Revises: f173a4793f99
Create Date: 2021-03-05 18:58:00.880951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7ca032ef2f'
down_revision = 'f173a4793f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_temp_pass', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_temp_pass')
    # ### end Alembic commands ###
