"""tutor application fields

Revision ID: d7d37230a902
Revises: 87e71d38bd47
Create Date: 2020-08-08 16:15:58.592883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d37230a902'
down_revision = '87e71d38bd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_application', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('tutor_application', sa.Column('phone', sa.String(length=14), nullable=True))
    op.add_column('tutor_application', sa.Column('subjects', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tutor_application', sa.Column('zip', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'tutor_application', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutor_application', type_='unique')
    op.drop_column('tutor_application', 'zip')
    op.drop_column('tutor_application', 'subjects')
    op.drop_column('tutor_application', 'phone')
    op.drop_column('tutor_application', 'name')
    # ### end Alembic commands ###
