"""empty message

Revision ID: e7e328c0c62e
Revises: e6b2af88ac61
Create Date: 2020-08-06 17:21:36.681494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7e328c0c62e'
down_revision = 'e6b2af88ac61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('application', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'user', 'tutor_application', ['application'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'application')
    # ### end Alembic commands ###
