"""empty message

Revision ID: f173a4793f99
Revises: f5d20b39cc36
Create Date: 2021-01-28 10:38:44.565094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f173a4793f99'
down_revision = 'f5d20b39cc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_page',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('page_id', sa.String(length=8), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('subjects', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=True),
    sa.Column('user', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_page_page_id'), 'tutor_page', ['page_id'], unique=True)
    op.create_index(op.f('ix_tutor_page_user'), 'tutor_page', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_page_user'), table_name='tutor_page')
    op.drop_index(op.f('ix_tutor_page_page_id'), table_name='tutor_page')
    op.drop_table('tutor_page')
    # ### end Alembic commands ###
