"""empty message

Revision ID: f5d20b39cc36
Revises: ebd28d613499
Create Date: 2021-01-06 14:40:23.683936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5d20b39cc36'
down_revision = 'ebd28d613499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('feedback_type', sa.Enum('HELP', 'ISSUE', 'FEEDBACK', name='feedback_type'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROCESS', 'RESOLVED', name='feedback_status'), nullable=True),
    sa.Column('submitted_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_submitted_by'), 'feedback', ['submitted_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_submitted_by'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
