name: Deploy main to Prod
on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Create ZIP deployment package
      run: zip -r ${{ github.sha }}_deploy.zip ./

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: "us-west-1"

    - name: Upload package to S3 bucket
      run: aws s3 cp deploy_package.zip s3://elasticbeanstalk-us-west-1-663435045241/

    - name: Create new EB Application Version
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name h2e-backend \
        --source-bundle S3Bucket="elasticbeanstalk-us-west-1-663435045241",S3Key=${{ github.sha }}_deploy.zip \
        --version-label "ver-${{ github.sha }}" \
        --description "commit-sha-${{ github.sha }}"

    - name: Deploy new EB Application Version
      run: aws elasticbeanstalk update-environment --environment-name H2eBackend-prod --version-label "ver-${{ github.sha }}"
